# Konfigurasi Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/restoku_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfigurasi Hibernate/JPA
# ddl-auto=update -> Hibernate otomatis membuat/menyesuaikan tabel dari entity Java.
# Tidak perlu menjalankan file SQL manual lagi selama opsi ini aktif.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# JWT
# GANTI secret ini dengan string acak panjang & rahasia sebelum production.
app.jwt.secret=1d02b0bad39fb9b95f96f3c8e943e8e3a0647de35823debab2d1ef78bc1814cc
app.jwt.expiration-ms=86400000

# Midtrans (Sandbox) - GANTI dengan key asli dari dashboard.midtrans.com
midtrans.server-key=Mid-server-B7g7qII0MI70POKXEis7Z_wT
midtrans.client-key=Mid-client-IQtUdsIDKvzK3Mmd
midtrans.is-production=false
midtrans.snap-base-url-sandbox=https://app.sandbox.midtrans.com/snap/v1/transactions
midtrans.snap-base-url-production=https://app.midtrans.com/snap/v1/transactions

# Biaya layanan flat per pesanan (bisa diubah sesuai kebutuhan resto)
app.biaya-layanan=0

# Upload file (foto menu)
app.upload-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB